site_name: Hermetis
theme:
  name: material
  features:
    # - navigation.tabs
    - navigation.sections
    # - toc.integrate
    - navigation.top

nav:
  - 'quickStart.md'
  - 'overview.md'
  - 'specifications.md'
  - 'userGuide.md'
  - 'configuration.md'

# extra:
#   alternate:
#     - name: Español
#       link: /es/
#       lang: es


plugins:
  - i18n: #mkdocs-static-i18n/
      docs_structure: suffix
      languages:
        - locale: en
          default: true
          name: English
          build: true
        - locale: es
          name: Español
          build: true

markdown_extensions:
  - attr_list
  - pymdownx.critic
  - admonition
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
